let metadata = {
  journals: [
    'academic emergency medicine',
    'American Journal of Emergency Medicine',
    'annals of emergency medicine',
    'Canadian Journal of Emergency Medicine',
    'Critical Care Medicine',
    'emergency medicine australasia',
    'emergency medicine journal',
    'european journal of emergency medicine',
    'European Journal of Trauma and Emergency Surgery',
    'injury',
    'Internal and Emergency Medicine',
    'Prehospital and Disaster Medicine',
    'prehospital emergency care',
    'resuscitation',
    'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine',
    'shock',
    'The Journal of Emergency Medicine',
    'Western Journal of Emergency Medicine',
    'world journal of emergency surgery'
  ],

  years: [
    2016,
    2017
  ],

  pseudonyms: [
    'academic emergency medicine',
    'Academic Emergency Medicine',
    'American Journal of Emergency Medicine',
    'annals of emergency medicine',
    'Annals of Emergency Medicine',
    'Canadian Journal of Emergency Medicine',
    'Critical Care Medicine',
    'Critical care medicine', // CHECK 'CRITICAL CARE' IN 2016 AT SOME POINT
    'emergency medicine australasia',
    'EMA - Emergency Medicine Australasia',
    'Emergency medicine Australasia : EMA',
    'emergency medicine journal',
    'Emergency Medicine Journal',
    'Emergency medicine journal : EMJ',
    'european journal of emergency medicine',
    'European Journal of Emergency Medicine',
    'European Journal of Trauma and Emergency Surgery',
    'injury',
    'Injury',
    'Internal and Emergency Medicine',
    'Internal and Emergency Medicine',
    'Internal and emergency medicine',
    'Prehospital and Disaster Medicine',
    'Prehospital and disaster medicine',
    'prehospital emergency care',
    'Prehospital Emergency Care',
    'resuscitation',
    'Resuscitation',
    'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine',
    'Scandinavian Journal of Trauma resuscitation and Emergency Medicine',
    'Scandinavian Journal of Trauma, Resuscitation and Emergency Medicine',
    'Scandinavian journal of trauma, resuscitation and emergency medicine',
    'shock',
    'Shock',
    'The Journal of Emergency Medicine',
    'Journal of Emergency Medicine',
    'Western Journal of Emergency Medicine',
    'The western journal of emergency medicine',
    'world journal of emergency surgery',
    'World Journal of Emergency Surgery',
    'World journal of emergency surgery : WJES'
  ],

  pseudonymMatcher: {
    'academic emergency medicine': 'academic emergency medicine',
    'Academic Emergency Medicine': 'academic emergency medicine',
    'American Journal of Emergency Medicine': 'American Journal of Emergency Medicine',
    'annals of emergency medicine': 'annals of emergency medicine',
    'Annals of Emergency Medicine': 'annals of emergency medicine',
    'Canadian Journal of Emergency Medicine': 'Canadian Journal of Emergency Medicine',
    'Critical Care Medicine': 'Critical Care Medicine',
    'Critical care medicine': 'Critical Care Medicine',
    'emergency medicine australasia': 'emergency medicine australasia',
    'EMA - Emergency Medicine Australasia': 'emergency medicine australasia',
    'Emergency medicine Australasia : EMA': 'emergency medicine australasia',
    'emergency medicine journal': 'emergency medicine journal',
    'Emergency Medicine Journal': 'emergency medicine journal',
    'Emergency medicine journal : EMJ': 'emergency medicine journal',
    'european journal of emergency medicine': 'european journal of emergency medicine',
    'European Journal of Emergency Medicine': 'european journal of emergency medicine',
    'European Journal of Trauma and Emergency Surgery': 'European Journal of Trauma and Emergency Surgery',
    'injury': 'injury',
    'Injury': 'injury',
    'Internal and Emergency Medicine': 'Internal and Emergency Medicine',
    'Internal and emergency medicine': 'Internal and Emergency Medicine',
    'Prehospital and Disaster Medicine': 'Prehospital and Disaster Medicine',
    'Prehospital and disaster medicine': 'Prehospital and Disaster Medicine',
    'prehospital emergency care': 'prehospital emergency care',
    'Prehospital Emergency Care': 'prehospital emergency care',
    'resuscitation': 'resuscitation',
    'Resuscitation': 'resuscitation',
    'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine': 'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine',
    'Scandinavian Journal of Trauma resuscitation and Emergency Medicine': 'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine',
    'Scandinavian Journal of Trauma, Resuscitation and Emergency Medicine': 'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine',
    'Scandinavian journal of trauma, resuscitation and emergency medicine': 'Scandinavian Journal of Trauma Resuscitation and Emergency Medicine',
    'shock': 'shock',
    'Shock': 'shock',
    'The Journal of Emergency Medicine': 'The Journal of Emergency Medicine',
    'Journal of Emergency Medicine': 'The Journal of Emergency Medicine',
    'Western Journal of Emergency Medicine': 'Western Journal of Emergency Medicine',
    'The western journal of emergency medicine': 'Western Journal of Emergency Medicine',
    'world journal of emergency surgery': 'world journal of emergency surgery',
    'World Journal of Emergency Surgery': 'world journal of emergency surgery',
    'World journal of emergency surgery : WJES': 'world journal of emergency surgery'
  },

  displayNames: [
    'Academic Emergency Medicine',
    'American Journal of Emergency Medicine',
    'Annals of Emergency Medicine',
    'Canadian Journal of Emergency Medicine',
    'Critical Care Medicine',
    'Emergency Medicine Australasia',
    'Emergency Medicine Journal',
    'European Journal of Emergency Medicine',
    'European Journal of Trauma and Emergency Surgery',
    'Injury',
    'Internal and Emergency Medicine',
    'Prehospital and Disaster Medicine',
    'Prehospital Emergency Care',
    'Resuscitation',
    'Scandinavian Journal of Trauma, Resuscitation and Emergency Medicine',
    'Shock',
    'The Journal of Emergency Medicine',
    'Western Journal of Emergency Medicine',
    'World Journal of Emergency Surgery'
  ]
}

module.exports = metadata
